# Generated by Django 2.1.15 on 2023-10-26 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_sugar_level',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='body_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='respiratory_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='DEFAULT_VALUE_HERE', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='8940999340', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='raja@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
