# Generated by Django 2.1.15 on 2023-10-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_auto_20231026_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
