# Generated by Django 2.1.15 on 2023-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20231205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_sugar_level',
            field=models.CharField(max_length=20),
        ),
    ]
